version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: bigbig
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /srv/db:/var/lib/mysql
    restart: always

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    restart: always
